
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class ClintLogin extends javax.swing.JFrame {

    String a;
    public ClintLogin() {
        initComponents();
        clintloginusername.setBackground(new java.awt.Color(0,0,0,1));
        clintloginpwd.setBackground(new java.awt.Color(0,0,0,1));
        
        scaleclintbackImage();
        scalebackImage();
        scaledrImage();
        
    }
/**
     * Creates new form ClintLogin
     */
         String shown;
     
     public void scaleclintbackImage() {
 ImageIcon icon = new ImageIcon("C:\\Users\\ASUS\\Desktop\\java project\\adminback1.jpg");

 Image img = icon.getImage();
 Image imgScale = img.getScaledInstance(clintloginback.getWidth(), clintloginback.getHeight(), Image.SCALE_SMOOTH);
 ImageIcon scaledIcon = new ImageIcon(imgScale);
 clintloginback.setIcon(scaledIcon);
 }
    
     public void scalebackImage() {
 ImageIcon icon = new ImageIcon("C:\\Users\\ASUS\\Desktop\\java project\\back3.png");

 Image img = icon.getImage();
 Image imgScale = img.getScaledInstance(clback.getWidth(), clback.getHeight(), Image.SCALE_SMOOTH);
 ImageIcon scaledIcon = new ImageIcon(imgScale);
 clback.setIcon(scaledIcon);
 }
     
     public void scaledrImage() {
 ImageIcon icon = new ImageIcon("C:\\Users\\ASUS\\Desktop\\java project\\dr.png");

 Image img = icon.getImage();
 Image imgScale = img.getScaledInstance(drlogo.getWidth(), drlogo.getHeight(), Image.SCALE_SMOOTH);
 ImageIcon scaledIcon = new ImageIcon(imgScale);
 drlogo.setIcon(scaledIcon);
     }
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu3 = new javax.swing.JPopupMenu();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        clintloginusername = new javax.swing.JTextField();
        clintloginhomepage = new javax.swing.JButton();
        clintloginpwd = new javax.swing.JPasswordField();
        clback = new javax.swing.JLabel();
        drlogo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        clintloginback = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        jButton1.setText("jButton1");

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("User Login");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, -1, -1));

        clintloginusername.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        clintloginusername.setForeground(new java.awt.Color(255, 255, 255));
        clintloginusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                clintloginusernameKeyPressed(evt);
            }
        });
        getContentPane().add(clintloginusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 210, 40));

        clintloginhomepage.setText("Go back to Homepage");
        clintloginhomepage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clintloginhomepageActionPerformed(evt);
            }
        });
        getContentPane().add(clintloginhomepage, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 10, -1, -1));

        clintloginpwd.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        clintloginpwd.setForeground(new java.awt.Color(255, 255, 255));
        clintloginpwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clintloginpwdActionPerformed(evt);
            }
        });
        clintloginpwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                clintloginpwdKeyPressed(evt);
            }
        });
        getContentPane().add(clintloginpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 500, 210, 40));

        clback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clbackMouseClicked(evt);
            }
        });
        getContentPane().add(clback, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 50, 40));
        getContentPane().add(drlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 130, 160));

        jLabel6.setFont(new java.awt.Font("Sitka Text", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Welcome to ABC Medical Services");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 580, 100));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("          Login");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 570, 210, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Register As a User");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 640, -1, -1));
        getContentPane().add(clintloginback, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1470, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clintloginhomepageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clintloginhomepageActionPerformed
Homepage hlogin= new Homepage();
hlogin.show();

dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_clintloginhomepageActionPerformed

    private void clbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clbackMouseClicked
Homepage hlogin= new Homepage();
hlogin.show();

dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_clbackMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
                 if(clintloginusername.getText().trim().isEmpty() && clintloginpwd.getText().trim().isEmpty())
{
JOptionPane.showMessageDialog(this, "Username and Password is empty");
}
         else if(clintloginusername.getText().trim().isEmpty())
{
JOptionPane.showMessageDialog(this, "Username is empty");
}
         else if(clintloginpwd.getText().trim().isEmpty())
{
JOptionPane.showMessageDialog(this, "Password is empty");
}

      try{  
			Class.forName("com.mysql.cj.jdbc.Driver");  
			Connection con=DriverManager.getConnection(  "jdbc:mysql://localhost:3306/medicalservices","root","");  
			//here btech is database name, root is username and password  
			Statement stmt=con.createStatement();
                        
String clintname=clintloginusername.getText() ;
String clintpassword=clintloginpwd.getText();

String sql="select * from user where Uname='"+clintname+"'and Upwd ='"+clintpassword+"'";
ResultSet rs=stmt.executeQuery(sql);
a=clintname;
if(rs.next()){
    dispose();
    Clintmainpage clintmainpage=new Clintmainpage();
    clintmainpage.showname1.setText("Hello "+clintname+" !");
    clintmainpage.show();
    JOptionPane.showMessageDialog(this, "Login Sucessfully");
    
    
}
else{
    JOptionPane.showMessageDialog(this, "username or password is invalid");
}

    
     
 
    con.close();
}catch(Exception e){ System.out.println(e);}  
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void clintloginusernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clintloginusernameKeyPressed
                clintloginusername.setBackground(new java.awt.Color(18,34,47));        // TODO add your handling code here:
    }//GEN-LAST:event_clintloginusernameKeyPressed

    private void clintloginpwdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clintloginpwdKeyPressed
       clintloginpwd.setBackground(new java.awt.Color(18,34,47));        // TODO add your handling code here:
    // TODO add your handling code here:
    }//GEN-LAST:event_clintloginpwdKeyPressed

    private void clintloginpwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clintloginpwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clintloginpwdActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
ClintRegister cRegister= new ClintRegister();
cRegister.show();

dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClintLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClintLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClintLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClintLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClintLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clback;
    private javax.swing.JLabel clintloginback;
    private javax.swing.JButton clintloginhomepage;
    private javax.swing.JPasswordField clintloginpwd;
    public static javax.swing.JTextField clintloginusername;
    private javax.swing.JLabel drlogo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPopupMenu jPopupMenu3;
    // End of variables declaration//GEN-END:variables
}
